%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: ...\FS_Training_Project\05_vehicleDriveAndControl\examples\driveCycleData.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB

%% Import the data
% Please edit path according to you system if required
[~, ~, raw] = xlsread('driveCycleData.xlsx','Sheet1','A4:D1004');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
PedalTime = data(:,1);
ThrottlePedal = data(:,2);
FrontBrakePedal = data(:,3);
RearBrakePedal = data(:,4);

%% Clear temporary variables
clearvars data raw R;
% Copyright 2018 The MathWorks, Inc.